### ISSUE TITLE
Vendor-Erweiterungen standardisieren

### ISSUE THREAD

**Issue by KimBrodowski** [Schulconnex/v1#11]
### Hintergrund
Ich arbeite als Softwarearchitekt bei der IServ GmbH, dem Marktführer für Schulplattformen in Deutschland mit rund 4 Millionen Nutzern. Die Issues hier erstelle ich für meinen Arbeitgeber.

Die IServ GmbH möchte den SchulConneX-Standard selbst nutzen. Dazu stehen wir mit verschiedenen Partnern in großen Projekten im Austausch. Mit Herrn Heithecker gab es hierzu auch bereits formlos Kontakt. Wir sind daran interessiert, uns an der Weiterentwicklung des Standards zu beteiligen.

### Issue
An verschiedenen Stellen der Spezifikation hätten wir als Anbieter eigener Software, auf allen Seiten der Schnittstelle, gerne die Möglichkeit, eigene Felder zu übertragen, ohne Kollisionen mit zukünftigen Versionen der API-Spezifikation zu erzeugen.

Zu diesem Zweck ist es üblich, solche Felder hinter eigene Prefixe zu stellen. Bei HTTP-Headern nutzen wir beispielsweise `X-IServ-...` .

Wir würden vorschlagen, eine ähnliche Strategie sowohl für Feldnamen als auch für Codelisten zu etablieren, also z.B. dem Fächerkanon. Insbesondere auch bei den Rollen im System sehen wir dort beispielsweise akuten Bedarf.

Für Bundesländer beispielsweise würden wir ein Prefix nach [ISO 3166-2:DE](https://de.wikipedia.org/wiki/ISO_3166-2:DE) vorschlagen, für alle anderen Organisationen `_kürzel` abgetrennt mit einem `.` oder ähnlichem.

**Comment by kaystrobach** [comment]
von schullogin werden wir dazu noch einen vorschlag machen, der auch einen validierung zuläßt, über feedback würden wir uns freuen. Grundidee wird so ähnlich wie die vendor extensions in scim sein.

**Comment by andrepaul** [comment]
Hallo Herr Brodowski. Tatsächlich sehen wir vor, dass wir mit Version 2 eine Umstellung der Codelisten auf IRIs und RDF Dokumente vornehmen wollen. In dem Zuge sollen Vendor Erweiterungen möglich ermöglicht werden.

**Comment by bwhdien** [comment]
Erledigt https://github.com/Schulconnex/Schulconnex/
