### ISSUE TITLE
Loeschung.Zeitpunkt Beispiel nicht korrekt in openapi Spezifikation

### ISSUE THREAD

**Issue by chrisburkh** [Schulconnex/v1#14]
In der Beschreibung für das Attribut Zeitpunkt im Objekt Löschung ist das Beispiel nicht korrekt:
```json
 "Loeschung" : {
        "required" : [ "zeitpunkt" ],
        "type" : "object",
        "properties" : {
          "zeitpunkt" : {
            "pattern" : "yyyy-MM-dd'T'kk:mm'Z'",
            "type" : "string",
            "description" : "String (datetime) - Datum und Uhrzeit der Löschung desPersonenkontexts Das Format des Löschzeitpunktes ist yyyy-MM-dd'T'hh:mm'Z' als UTC-Zeitpunkt. Solange ein Personenkontext nicht gelöscht wurde, kann das Attribut loeschzeitpunkt geändert oder gelöscht werden. Ist das Attribut loeschung vorhanden, so muss der Zeitpunkt gesetzt sein.",
            "format" : "date-time",
            "example" : "2023-12-01T10:40:00Z"
          }
        }
      }
```

Wenn man den Beispiel-Wert '2023-12-01T10:40:00Z' verwendet erhält man diesen Fehler:
```json
{
    "code": "400",
    "subcode": "09",
    "titel": "Datumsattribut hat einen ungültigen Wert",
    "beschreibung": "Datumsformat von Attribut loeschung.zeitpunkt ist ungültig."
}
```

**Comment by andrepaul** [comment]
Hallo @chrisburkh das angegebene Beispiel ist leider falsch. In sofern danke für den Hinweis. Entsprechend dem Pattern gibt es für die Zeitangabe keinen Sekundenanteil. Kommt die Fehlermeldung auch vor wenn der Request mit 2023-12-01T10:40Z ausgeführt wird? Falls ja können sie bitte den ganzen Request hier rein posten?

**Comment by chrisburkh** [comment]
Hallo,
wenn man den Zeitpunkt übergibt exakt so wie das Pattern ist, geht der Request durch.
Also es ist nur der Wert in dem _example_ falsch.

**Comment by andrepaul** [comment]
Ok danke für das Feedback. Das Beispiel wird im openapi der Dienste API angepasst damit es zum Template passt.
