### ISSUE TITLE
Falscher Code für Erreichbarkeitstyp E-Mail

### ISSUE THREAD

**Issue by MarvinOehlerkingCap** [Schulconnex/v1#15]
In 11.19 Erreichbarkeitstyp ist die Beschreibung des Codes für E-Mail falsch. Die moin.schule API für personen-info gibt für die erreichbarkeiten eines personenkontexts den Wert "E-Mail" statt "EMail" zurück.

**Comment by andrepaul** [comment]
Hallo Herr Öhlerking. Vielen Dank für den Hinweis. Wir haben die Spezifikation bereits angepasst sodass auch dort nun E-Mail als Code benutzt wird.
