### ISSUE TITLE
Fächerliste passt nicht zu Sachsen

### ISSUE THREAD

**Issue by wi-wissen** [Schulconnex/v1#16]
Das Land Sachsen spezifiziert seine Fächer in einer Verwaltungsvorschrift. Dabei tauchen andere Fächer auf und auch die Abkürzungen für etwa Biologie sind abweichend:

https://www.revosax.sachsen.de/law_versions/43228/pdf_attachments

**Comment by andrepaul** [comment]
Hallo @wi-wissen wir schauen, dass wir für Version 1.5 eine Rückwärtskompatible Lösung integrieren können. Spätestens mit Version 2 und der dort angedachten Anpassung der Codelisten zu URI basierten "Codes" ist geplant dass Länderspezifische Anpassungen Bestandteil werden.

**Comment by wi-wissen** [comment]
Aus meiner Sicht wäre das ausreichend. Uns ist das egal, andere würden sich aber vielleicht über einheitliche Fachkennungen freuen, dann hätte man Mathe immer gefunden. Vielleicht könnte das ein zusätzliches Attribut sein?

**Comment by bwhdien** [comment]
Erledigt https://github.com/Schulconnex/Schulconnex/
