### ISSUE TITLE
Geburtsort erlaubt keine Sonderzeichen über API, wie z.B. Schrägstrich( Slash) 

### ISSUE THREAD

**Issue by feuerholt** [SchulConneX/v1#3]
Im konkreten Beispiel 
Geburtsort in DaNiS: **Nienburg/Weser**

Fehlermeldung beim Synchronisieren:

`Nachname, Rufname(6a, JgStufe 6)...  Error in updatePerson
status: 400
Response: {"code":"400","subcode":"08","titel":"Attributwerte entsprechen nicht dem gültigen Zeichensatz","beschreibung":"Text von Attribut oder Query Parameter geburt.geburtsort entspricht nicht dem Zeichensatz DIN 91379.A."}`

Wenn ich jedoch auf der Webseite den Geburtsort "Nienburg/Weser" eintrage, dann wird dieser akzeptiert

**Comment by andrepaul** [comment]
Hallo feuerholt. Der Datentyp wird künftig auf DIN 91379.C angepasst um hier auch mit XMELD kompatibel zu sein. Damit ist dann unter anderem auch der Slash möglich.
