### ISSUE TITLE
 OpenAPI-Spezifikation bereitstellen

### ISSUE THREAD

**Issue by KimBrodowski** [Schulconnex/v1#9]
### Hintergrund
Ich arbeite als Softwarearchitekt bei der IServ GmbH, dem Marktführer für Schulplattformen in Deutschland mit rund 4 Millionen Nutzern. Die Issues hier erstelle ich für meinen Arbeitgeber.

Die IServ GmbH möchte den SchulConneX-Standard selbst nutzen. Dazu stehen wir mit verschiedenen Partnern in großen Projekten im Austausch. Mit Herrn Heithecker gab es hierzu auch bereits formlos Kontakt. Wir sind daran interessiert, uns an der Weiterentwicklung des Standards zu beteiligen.

### Issue
Wir würden uns wünschen, dass die Spezifikation neben einem PDF-Dokument auch als [OpenAPI-Spezifikation](https://www.openapis.org/) bereitgestellt wird. Dies bringt folgende Vorteile:

* Änderungen sind trivial über Diffs einsehbar, maschinenlesbar, auch ohne dediziertes Changelog
* Einfache Erstellung von API-Clients (Code Generierung) und Mock-Endpunkten zum Testen von Anwendungen
* Vertrautes und standardisiertes Format für Entwickler
* Barrierefreie und dynamische Renderer wie Swagger, kein eigenes Darstellungsformat nötig.

**Comment by fstueber** [comment]
Ein OpenAPI-Spezifikation für SchulConneX wäre in der Tat eine prima Sache. 

Ich würde sogar noch einen Schritt weitergehen, und anregen, die gesamte Spezifikation Git-kompatibel zu machen. 

PDF ist kein brauchbares Format für Git. Ja, man kann natürlich ein PDF-Dokument unter Git speichern, aber eine Nachvollziehbarkeit der Änderungen via Diff ist nur schlecht möglich. Zudem ist das Lesen eines PDF auf Dauer etwas unhandlich, vor allem wenn es um Beispiele geht, die sich über mehrere PDF-Seiten erstrecken.

Die gesamte SchulConneX-Spezifikation könnte in drei Teile aufgeteilt werden:

+ **OpenAPI:** Syntaktische und semantische Spezifikation von SchulConneX. Praktisch gesehen sind dies ein oder mehre generierte JSON-Dateien, die hier unter Git abgelegt werden. 
  
+ **Statische Webseite:** Einführung, Motivation und Erläuterung von SchulConneX. Also der Inhalt des PDFs als eine Serie von Markdown-Dateien, aus denen via Git-Actions eine statische Website generiert wird, die ebenfalls unter GitHub-Pages (z.B. https://SchulConneX.github.io/v1/) publiziert wird. 
  
+ **Beispiele:** Möglichst vollständige Beispiele für API-Requests und API-Responses, die als JSON-Dateien ebenfalls unter Git abgelegt werden und auf die von der Dokumentation (also der statischen Webseite) aus verwiesen werden kann. 
 
Einmal eingerichtet, können Änderungen jederzeit per Commit publiziert werden.

+ Vorteile für die Entwickler (neben den oben bereits erwähnten): 
  
  + Automatische Benachrichtigung, wenn es Änderungen gegeben hat (inklusive dem Was? Wer? Wo?).
  
  + Mit einem Diff können auch kleinste, fokussierte Änderungen an der Spezifikation (egal ob OpenAPI, Webseite oder Beispiele) wunderbar nachvollzogen werden.
  
  + Die Suche innerhalb der Spezifikation wäre höchst effizient.
 
+ Vorteile für die Owner:

  + Vollständige Historie aller Änderungen (wer hat wann was genau geändert, hinzugefügt oder gelöscht)
  
  + Möglichkeit der semantischen Versionierung der Spezifikation mittels Git-Tags.
  
  + Alles voll automatisiert (via GitHub-Actions) ohne zusätzliche Ressourcen.
  
  + Eine richtige Webseite wäre viel sichtbarer im Web.

  + Und cool aussehen tut das Ganze auch noch ;-)
  
Auch wir als STÜBER SYSTEMS GmbH (Hersteller für Software in der Schulverwaltung) sind gerne bereit, hier mitzuhelfen.

**Comment by andrepaul** [comment]
Hallo Herr Brodowski, hallo Herr Stüber. Zum Thema OpenAPI als auch zum Thema Git basierte Spezifikationen kann ich mitteilen, dass beides auf der Roadmap ist. Es wird in kürze zumindest noch die 1.4 als PDF erscheinen wir sind allerdings bereits in der Planung die Spezifikation neu aufzustellen und vom PDF weg zu kommen. Bzgl. OpenAPI kann durchaus die OpenAPI Beschreibung von MoinSchule benutzt werden da MoinSchule als Referenzimplementierung der Serverseite dient.

**Comment by chrisburkh** [comment]
@andrepaul 
Hallo Herr Paul,

wo kann man denn die OpenAPI Beschreibung von MoinSchule finden?

**Comment by andrepaul** [comment]
Hallo Herr Burkhardt (@chrisburkh), die beiden Schnittstellen zum MoinSchule Server sind hier zu finden:

Quellsystem API: https://api-schulen.stage.niedersachsen-login.schule/v1/api-docs?tryItOutEnabled=false&url=openapi.json 
Dienste API: https://api-dienste.stage.niedersachsen-login.schule/v1/api-docs?tryItOutEnabled=false&url=openapi.json

**Comment by bwhdien** [comment]
Erledigt https://github.com/Schulconnex/Schulconnex/
